# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: CheCo Media Blue
email: your-email@domain.com
author: CheCo
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2015 CheCo Media Blue . All Rights Reserved.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://twitter.com/SBootstrap
  - title: youtube
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: instagram
    url: 
